spring:
  application:
    name: spring-kafka-app
  docker:
    compose:
      enabled: true
      file: docker-compose-redpanda.yaml
  kafka:
    bootstrap-servers: localhost:19092
    streams:
      bootstrap-servers: localhost:19092
      application-id: word-counter-stream
    consumer:
      group-id: spring-word-consumer
      auto-offset-reset: earliest


